shows:
  - canonical-id: "zdf-magazin-royale-102"
    filter:
      minDate: "2024-03-18 00:00+00:00"
    download:
      folder: "/serien/ZDF Magazin Royale"
      filename: "ZDF Magazin Royale"
interval: 60
